name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.20.0-dev.1
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  foundation_fluttify: ^0.13.0+1
  core_location_fluttify: ^0.7.1

  amap_core_fluttify:
    git:
      url: git@github.com:mature-road/dl_core_amap.git
      ref: 890b43d6a32919acd68558c162dde20652042ac8

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin
